version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # management UI
      - "61613:61613"   # STOMP
      - "15674:15674"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_web_stomp &&
               docker-entrypoint.sh rabbitmq-server"
